#pragma bank 255

#include <gbdk/platform.h>

/*

 BKG_P_RANK.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(BKG_P_RANK)
const unsigned char BKG_P_RANK[] =
{
  0x00,0x7F,0x40,0x40,0x4F,0x4F,0x4F,0x40,
  0x40,0x4F,0x4F,0x4F,0x4F,0x4F,0x7F,0x00,
  0x00,0xFE,0x0E,0x06,0xF2,0xF2,0xF2,0x06,
  0x0E,0xFE,0xFE,0xFE,0xFE,0xFE,0xFE,0x00
};

/* End of BKG_P_RANK.C */
