#pragma bank 255

#include <gbdk/platform.h>

/*

 BKG_CHECKPOINT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 123 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(BKG_CHECKPOINT)
const unsigned char BKG_CHECKPOINT[] =
{
  0xFF,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF,
  0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,
  0x00,0x3C,0x68,0x68,0x3C,0x3C,0x66,0x00
};

/* End of BKG_CHECKPOINT.C */
