#pragma bank 255

#include <gbdk/platform.h>

/*

 BKG_CONVEYORS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 7 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(BKG_CONVEYORS)
const unsigned char BKG_CONVEYORS[] =
{
  0x7E,0xC3,0x95,0xA9,0xA9,0x95,0xC3,0x7E,
  0x7E,0xC3,0xA9,0x95,0x95,0xA9,0xC3,0x7E
};

/* End of BKG_CONVEYORS.C */
