#pragma bank 255

#include <gbdk/platform.h>

/*

 BKG_FACTORY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(BKG_FACTORY)
const unsigned char BKG_FACTORY[] =
{
  0xF7,0xEF,0xF7,0xEF,0xF7,0xEF,0xF7,0xEF,
  0xFF,0xFF,0x99,0x66,0x66,0x99,0xFF,0xFF
};

/* End of BKG_FACTORY.C */
