#pragma bank 255

#include <gbdk/platform.h>

/*

 BKG_SPIKES_SPRING.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 2 to 6

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(BKG_SPIKES_SPRING)
const unsigned char BKG_SPIKES_SPRING[] =
{
  0x18,0x24,0x42,0x81,0x81,0x81,0x81,0x81,
  0xF8,0x04,0x02,0x01,0x01,0x02,0x04,0xF8,
  0x81,0x81,0x81,0x81,0x81,0x42,0x24,0x18,
  0x1F,0x20,0x40,0x80,0x80,0x40,0x20,0x1F,
  0xFF,0x42,0x24,0x18,0x18,0x24,0x42,0xFF
};

/* End of BKG_SPIKES_SPRING.C */
