#pragma bank 255

#include <gbdk/platform.h>

/*

 SPR_LEAD_KID.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(SPR_LEAD_KID)
const unsigned char SPR_LEAD_KID[] =
{
  0x00,0x00,0x0F,0x0F,0x19,0x39,0x38,0x1C,
  0x0F,0x0F,0x0F,0x1F,0x21,0x1E,0x00,0x00,
  0x00,0x00,0xF0,0xF0,0x20,0x20,0x00,0x90,
  0x0F,0x0F,0x1F,0x2F,0x22,0x1C,0x00,0x00,
  0x00,0x00,0x0F,0x0F,0x1A,0x3A,0x38,0x1C
};

/* End of SPR_LEAD_KID.C */
