#pragma bank 255

#include <gbdk/platform.h>

/*

 SPR_BOSS_FACTORY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(SPR_BOSS_FACTORY)
const unsigned char SPR_BOSS_FACTORY[] =
{
  0xFF,0x84,0xB6,0xB7,0x87,0xA7,0xA7,0xB7,
  0x83,0xB1,0xE0,0x80,0x80,0x99,0x99,0xFF,
  0xFF,0x02,0x72,0x22,0x82,0xC0,0xE1,0xFF,
  0xFF,0xFE,0xDC,0x58,0x00,0x99,0x99,0xFF,
  0xCF,0xB6,0xB4,0x48,0x00,0x99,0x99,0xFF
};

/* End of SPR_BOSS_FACTORY.C */
