#pragma bank 255

#include <gbdk/platform.h>

/*

 SPR_TREASURE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
BANKREF(SPR_TREASURE)
const unsigned char SPR_TREASURE[] =
{
  0x7F,0x80,0x83,0x83,0x81,0x81,0xFF,0xFF,
  0x80,0x82,0x85,0x85,0x84,0x83,0x80,0xFF,
  0x01,0x41,0xE1,0x61,0xE1,0xC1,0x01,0xFF
};

/* End of SPR_TREASURE.C */
