#pragma once

BANKREF_EXTERN(BKG_UPPERCASE)
extern const uint8_t BKG_UPPERCASE[];
BANKREF_EXTERN(BKG_LOWERCASE)
extern const uint8_t BKG_LOWERCASE[];
BANKREF_EXTERN(BKG_CHECKPOINT)
extern const uint8_t BKG_CHECKPOINT[];

BANKREF_EXTERN(BKG_SPIKES_SPRING)
extern const uint8_t BKG_SPIKES_SPRING[];
BANKREF_EXTERN(BKG_CONVEYORS)
extern const uint8_t BKG_CONVEYORS[];
BANKREF_EXTERN(BKG_P_RANK)
extern const uint8_t BKG_P_RANK[];

BANKREF_EXTERN(BKG_FACTORY)
extern const uint8_t BKG_FACTORY[];

BANKREF_EXTERN(BKG_TITLE_SCREEN)
extern const uint8_t BKG_TITLE_SCREEN[];
BANKREF_EXTERN(BKG_NUMBERS)
extern const uint8_t BKG_NUMBERS[];
BANKREF_EXTERN(BKG_DR_AGON_LOGO)
extern const uint8_t BKG_DR_AGON_LOGO[];
