#ifndef MAP_DATA_H_
#define MAP_DATA_H_

extern const uint8_t MAP_BLANK[];

BANKREF_EXTERN(MAP_FACTORY_0)
extern const uint8_t MAP_FACTORY_0[];
BANKREF_EXTERN(MAP_FACTORY_1)
extern const uint8_t MAP_FACTORY_1[];
BANKREF_EXTERN(MAP_FACTORY_10)
extern const uint8_t MAP_FACTORY_10[];
BANKREF_EXTERN(MAP_FACTORY_11)
extern const uint8_t MAP_FACTORY_11[];
BANKREF_EXTERN(MAP_FACTORY_100)
extern const uint8_t MAP_FACTORY_100[];
BANKREF_EXTERN(MAP_FACTORY_101)
extern const uint8_t MAP_FACTORY_101[];
BANKREF_EXTERN(MAP_FACTORY_110)
extern const uint8_t MAP_FACTORY_110[];
BANKREF_EXTERN(MAP_FACTORY_111)
extern const uint8_t MAP_FACTORY_111[];
BANKREF_EXTERN(MAP_FACTORY_1000)
extern const uint8_t MAP_FACTORY_1000[];
BANKREF_EXTERN(MAP_FACTORY_1001)
extern const uint8_t MAP_FACTORY_1001[];
BANKREF_EXTERN(MAP_FACTORY_1010)
extern const uint8_t MAP_FACTORY_1010[];
BANKREF_EXTERN(MAP_FACTORY_1011)
extern const uint8_t MAP_FACTORY_1011[];
BANKREF_EXTERN(MAP_FACTORY_1100)
extern const uint8_t MAP_FACTORY_1100[];
BANKREF_EXTERN(MAP_FACTORY_1101)
extern const uint8_t MAP_FACTORY_1101[];
BANKREF_EXTERN(MAP_FACTORY_1110)
extern const uint8_t MAP_FACTORY_1110[];
BANKREF_EXTERN(MAP_FACTORY_1111)
extern const uint8_t MAP_FACTORY_1111[];
BANKREF_EXTERN(MAP_FACTORY_10000)
extern const uint8_t MAP_FACTORY_10000[];

BANKREF_EXTERN(MAP_TITLE_SCREEN)
extern const uint8_t MAP_TITLE_SCREEN[];

#endif
