#pragma once

BANKREF_EXTERN(MUS_TITLE)
extern const hUGESong_t MUS_TITLE;

BANKREF_EXTERN(MUS_FACTORY)
extern const hUGESong_t MUS_FACTORY;

BANKREF_EXTERN(MUS_BOSS)
extern const hUGESong_t MUS_BOSS;

BANKREF_EXTERN(MUS_LV_CLEAR)
extern const hUGESong_t MUS_LV_CLEAR;
BANKREF_EXTERN(MUS_LV_CLEAR_P_RANK)
extern const hUGESong_t MUS_LV_CLEAR_P_RANK;
